name = "tolya-vine-api"
main = "api/index.js"
compatibility_date = "2023-10-30"

# Это место для привязки нашего хранилища Cloudflare KV.
# Когда вы создадите его в панели управления Cloudflare, вы вставите сюда ID.
[[kv_namespaces]]
binding = "VINE_KV"
id = "ca3fa991ebf84e7daa9946036bfbf302"
preview_id = "ca3fa991ebf84e7daa9946036bfbf302"
