name = "tolya-vine-api"
main = "api/index.js"
compatibility_date = "2023-10-30"

# Это место для привязки нашего хранилища Cloudflare KV.
# Когда вы создадите его в панели управления Cloudflare, вы вставите сюда ID.
[[kv_namespaces]]
binding = "VINE_KV"
id = "вставьте_ваш_id_здесь"
preview_id = "вставьте_ваш_preview_id_здесь"
